# Constants....

IP_SERVER = '127.0.0.1'
PORT = 9091
PORT_HTTP = 80
ENCONDING_FORMAT = 'utf-8'
RECV_BUFFER_SIZE = 4096
BACKLOG = 5
HELO = 'HELO'
DATA = 'DATA'
QUIT = 'QUIT'
GET = 'GET'
POST = 'POST'
PUT = 'PUT'
DELETE = 'DELETE'
HEAD = 'HEAD'
#PATH = 'D:\UNIVERSIDAD\"Semestre 7"\Telematica\Proyecto2\files'